import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// The no-restricted-imports block that used to live here banned next/headers,
// next/server, next/cache and server-only, because the Bluehost host had no
// Node runtime and those imports would have failed at build time. On Vercel
// they all work, so the ban is gone: API routes, middleware, server actions
// and ISR are available.
const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Payload and rewritten on every schema change - editing
    // either to satisfy a lint rule would be undone by the next generate.
    "migrations/**",
    "app/(payload)/admin/importMap.js",
    "payload-types.ts",
  ]),
]);

export default eslintConfig;
